config/routes.rb
BootstrapOnRails::Application.routes.draw do

  

  get "comments/index"

  get "comments/new"

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions
  resources :password_resets
  
  resources :identities
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  

  resources :blogs do
    resources :comments
    member do
      get 'crop'
      put 'crop_update'
      post 'vote'
    end
  end
  resources :comments
  resources :users do
    resources :blogs
    member do
      get 'crop'
      put 'crop_update'
    end
  end
  get "admin/index"
  get "admin" => "admin#index"
  get "blog_archive/index"
  
  
  root :to => "home#index"  
  
  get "sugestions/index"
  get "sugestions/show" 
  

end

app/controllers/blog_archive_controller.rb
class BlogArchiveController < ApplicationController
  respond_to :html, :xml, :json
  
  def index
    @blogs = Blog.all
    respond_with(@blogs)

  end
end

app/helpers/blog_archive_helper.rb
module BlogArchiveHelper
end

app/views/blog_archive/index.html.slim
= render 'shared/navigation_menu'
.container
  .content
    = render 'shared/breadcrumbs', :breadcrumbs => @breadcrumbs unless @breadcrumbs.nil?
    .page-header
      h1 Blog indlæg<small>&nbsp;Historisk arkiv</small>
    == render 'shared/messages'
  
 

    .data-table
      table id="blogs" class="display"
        thead
          tr
            th Title
            /th Body
            th Af
            th Skrevet
            th Image
            th Pdf download
            th

        tbody
          - @blogs.each do |blog|
            tr
              td =link_to blog.title, blog
              td = blog.user.name
              td = blog.created_at.strftime("%d-%m-%Y")
              td
                -if blog.image_url != '/assets/fallback/default.png'
                  =link_to 'vis', blog.image_url
                
              td 
                -if blog.pdf_download_url != '/assets/fallback/default.pdf'
                  =link_to 'download', blog.pdf_download_url
              td 
                = link_to 'Vis', blog
                -if can_edit?
                  '&nbsp;
                  = link_to 'Rediger', edit_blog_path(blog)
                  '&nbsp;
                  = link_to 'Slet', blog, :confirm => 'Are you sure?', :method => :delete
    
    br
    -if user_signed_in?
      = link_to 'Skriv indlæg', new_user_blog_path(current_user), class: 'btn btn-primary btn-large'