config/routes.rb
BootstrapOnRails::Application.routes.draw do

  

  get "comments/index"

  get "comments/new"

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions
  resources :password_resets
  
  resources :identities
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  

  resources :blogs do
    resources :comments
    member do
      get 'crop'
      put 'crop_update'
      post 'vote'
    end
  end
  resources :comments
  resources :users do
    resources :blogs
    member do
      get 'crop'
      put 'crop_update'
    end
  end
  get "admin/index"
  get "admin" => "admin#index"
  get "blog_archive/index"
  
  
  root :to => "home#index"  
  
  get "sugestions/index"
  get "sugestions/show" 
  

end

app/views/shared/_breadcrumbs.html.slim
ul class="breadcrumb"
  /- [:notice, :warning, :error, :failure, :success].each do |key|
  - breadcrumbs.each do |name, url|
    li =link_to "#{name}", "#{url}"
    span class="divider" &#47;

app/views/shared/_error_messages.html.slim
-if taget.errors.any?
  div class="alert alert-error"
    = link_to 'x', '#', :class => 'close', :'data-dismiss' => 'alert'
    h3 = "#{pluralize(taget.errors.count, "error")}  prohibited this record from being saved:"
    ul
      - taget.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_log_in_modal.html.slim
.modal.fade id="loginModal"
  .modal-header
    a class="close" data-dismiss="modal"
      '×
    h3 Log ind

    .modal-body
      = form_tag "/auth/identity/callback" do
        .field
          = label_tag :auth_key, "Email"
          br
          = text_field_tag :auth_key

        .field
          = label_tag :password
          br
          = password_field_tag :password 

        /.actions
        /  = submit_tag "Login" 

        .modal-footer
          = link_to 'Ikke medlem endnu?', new_identity_path
          '&nbsp;  &nbsp;
          = link_to 'Glemt password?', new_password_reset_path
          '&nbsp;  &nbsp; &nbsp;  &nbsp;
          = submit_tag  'Log ind', :class =>"btn btn-primary btn-large"
          a href="#" class="btn btn-large" data-dismiss="modal"
            'Fortryd
        /h3 Log ind med
        .social-login
          
          =link_to 'Log ind med Twitter', "/auth/twitter/", class: 'btn btn-large btn-info'
          '&nbsp;
          =link_to 'Log ind med Facebook', "/auth/facebook/", class: 'btn btn-large btn-primary'
          br

app/views/shared/_messages.html.slim
- flash.each do |name, msg|
  div class="alert alert-#{name == :notice ? "success" : "error"}
    = link_to 'x', '#', :class => 'close', :'data-dismiss' => 'alert'
    = msg

app/views/shared/_navigation_menu.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"

      a class="brand" href="#{root_path}"STORFORSKEL
      .nav-collapse
        ul class="nav
          - if can_edit?
            li = link_to 'ADMIN', admin_index_path
          
          - if user_signed_in?
            li
              = link_to 'MIN KONTO', current_user
          li
            - if user_signed_in?
              = link_to 'LOG UD', signout_path
            -else
              a data-toggle="modal" href="#loginModal" rel="nofollow"
                'LOG IND
          li
            =link_to 'BLOG', blogs_path
          


    

app/views/shared/_popover.html.erb
<script>
  $(function () {
    $("a[rel=popover]")
      .popover({
        offset: 10
      })
      .click(function(e) {
        e.preventDefault()
      })
  })
</script>

app/views/shared/_twipsy.html.slim
javascript:
  $(function() {
    $("a[rel=twipsy]").twipsy({
      live: true
    });
  });