config/routes.rb
BootstrapOnRails::Application.routes.draw do

  

  get "comments/index"

  get "comments/new"

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions
  resources :password_resets
  
  resources :identities
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  

  resources :blogs do
    resources :comments
    member do
      get 'crop'
      put 'crop_update'
      post 'vote'
    end
  end
  resources :comments
  resources :users do
    resources :blogs
    member do
      get 'crop'
      put 'crop_update'
    end
  end
  get "admin/index"
  get "admin" => "admin#index"
  get "blog_archive/index"
  
  
  root :to => "home#index"  
  
  get "sugestions/index"
  get "sugestions/show" 
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    session[:go_to] = root_path
    @blogs = Blog.search(params[:search]).order("created_at desc").page(params[:page]).per(10)
  end

end

app/views/home/_contact.html.erb
<h4>
  <a href="http://synthmax.dk/storforskel/presseinformation.pdf">Download presse info</a>
  <br/>
  <a href="http://synthmax.dk/storforskel/preasentation.pdf">Præsentation</a>
  <br/>
  Telofon: 22 71 99 48
  <br/>
  <a href="mailto:morten@storforskel.nu">email: morten@storforskel.nu</mail_to>
  
  
</h4>

app/views/home/_ustream.html.erb
<iframe width="480" height="296" src="http://www.ustream.tv/embed/11534454" scrolling="no" frameborder="0" style="border: 0px none transparent;">    </iframe>
<br /><a href="http://www.ustream.tv/" style="padding: 2px 0px 4px; width: 400px; background: #ffffff; display: block; color: #000000; font-weight: normal; font-size: 10px; text-decoration: underline; text-align: center;" target="_blank">Live broadcast by Ustream</a>

app/views/home/index.html.slim
= render 'shared/navigation_menu'

.container
  .row
    .span9
      .super-size
        .logo
          =image_tag 'regnbuelogo.png'
        h1 Storforskel.nu
        p skaper positiv energi og fantastiske projekter i lokalområdet
        /- unless user_signed_in?
        /  a class="btn btn-primary btn-large"  data-toggle="modal" href="#loginModal" rel="nofollow"
        /    'Sign In
    .span3
      =render 'contact'
  .row
    .span12
      .youtube
        iframe width="770" height="433" src="http://www.youtube.com/embed/ABTlpB1IKKE?wmode=transparent" frameborder="0" allowfullscreen
        /?wmode=transparent !!! added to enable modal dialog on top on IE
      /==render 'ustream'

  - @blogs.each do |blog|
    ==render 'blogs/short_artichle', :blog => blog
    
    
    
    
    
    
        

  

app/views/home/index.mobile.slim
- content_for :head do
  meta name="viewport" content="initial-scale=1, maximum-scale=1"

.type-home data-role="page"

  .foo data-role="header"
    h1 STORFORSKEL.NU
  
  
  .foo data-role="content"
    .content-secondary
      #jqm-homeheader
        .logo
          =image_tag 'regnbuelogo.png'
      .intro
        strong STORFORSKEL.NU &nbsp;
        'skaper positiv energi og fantastiske projekter i lokalområdet
      /iframe width="770" height="433" src="http://www.youtube.com/embed/WdA86eK0Jp4" frameborder="0" allowfullscreen
      
      ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="f"
        li data-role="list-divider"
          a href="http://www.youtube.com/watch?v=WdA86eK0Jp4"
            'Se Videoen
        
        - if current_user
          li class="log_out" = link_to 'Log out', log_out_path
        - else
          li =link_to 'Log in', log_in_path
          /li = link_to 'Sign up', sign_up_path
        /li =link_to 'Posts', posts_path
        /li =link_to 'Users', users_path

    .content-primary

app/views/home/x_blog.slim
.blog
  h3#{blog.title}
  .row
    .span4
      .avatar
        =link_to image_tag(blog.user.image_url :thumb), blog.user
      .author
        h5 Af #{link_to blog.user.name, blog.user} 
        i skrevet for #{distance_of_time_in_words(Time.now, blog.created_at)} siden
        =pluralize blog.reputation_value_for(:votes).to_i, "vote"
        'hfhfh
        = link_to "up", vote_blog_path(blog, type: "up"), method: "post"
        ==render 'blogs/links', :blog => blog
        
      .content
    .span4
      =simple_format blog.body.truncate(264)
      br
      =link_to 'Læs hele artikelen og komentarer', blog
hr
      
      